// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syjeziswslasrxbgpjxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5amV6aXN3c2xhc3J4Ymdwanh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDc4OTQsImV4cCI6MjA2MjI4Mzg5NH0.C6-AUqE8WYqzXBfeHWKjhZAHe_y_nM36WEtOF3_ZS20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);